name: ToDoux CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install --legacy-peer-deps

      - name: 🛠️ Install Web Tools
        run: npx expo install react-native-web react-dom @expo/webpack-config -- --legacy-peer-deps

      - name: 🏗️ Build Web
        run: npx expo export:web

      - name: 🚀 Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-build
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}